### ISSUE TITLE
Struggling to Compile...

### ISSUE THREAD

**Issue by perrelet** [leadedge/ShaderLoader#2]
Hello,

Just wondering what the easiest way to compile the source is?

I thought I'd try using the dependencies from "shaderMaker" as a framework for shaderLoader, but got lots of compile errors. (C2555)

Am I missing something obvious here?

Many thanks for your time.

**Comment by leadedge** [comment]
Very sorry for taking so long to check this. I have not included the ShadeLoader project files because they depend on the folder setup for FreeframeGL 1.5.

If you can set up FreeframeGL and build one of the example plugins, it should be possible to create a new project based on one of these and add the ShaderLoader source files. This might be the easiest way.

**Comment by perrelet** [comment]
Hey there,

Got around to looking back into this.
Took your advice and got FreeframeGL building example plugins as expected.
Made a copy of one of the projects and used shaderLoader source... Here's what I got:

issue #1 (not a biggy):
L_READ_FRAMEBUFFER_EXT is apparently not defined so I set it in shaderloader.h as 0x8CA8 (from shaderMaker)

issue #2 (headache):
I'm getting about 10 LNK2019 errors - example:

`LNK2019	unresolved external symbol "public: __thiscall FFGLExtensions::FFGLExtensions(void)" (??0FFGLExtensions@@QAE@XZ) referenced in function "public: __thiscall ShaderLoader::ShaderLoader(void)" (??0ShaderLoader@@QAE@XZ)	FFGLBrightness2	E:\FFGLSDK_1_5\Projects\FFGLPlugins\MSVC_8\ShaderLoader.obj	1	
`
Not sure where to begin on this? A problem in my Linker settings?

Any help would be *much* appreciated!

Thanks,

Jamie :)

**Comment by perrelet** [comment]
Hey leadedge,

Just got around to diving back into this and am now hitting a major block. Followed your instruction and got both FFGL example plugins to compile and also a plugin using the ShaderLoader source - great. Problem - the compiled ShaderLoader .dll crashes Resolume (and any other host I've tried)...

Bit vague I know.... Any suggestions at all on how to go about testing?

Your help would be very much appreciated :)

**Comment by perrelet** [comment]
Hey again - some updates:

After running the plugin in the delphi host I get this the following log:

```
[ PluginInfoStruct ]
 
API MajorVersion: 1
API Minor Version: 0
Unique ID: IIII
Name : Shader Loader 2
Type: Effect
 
[ Plugin Capabilities ]
 
16bit: No
24bit: No
32bit: No
ProcessFrameCopy: No
ProcessOpenGL: Yes
Supports SetTime: No
Min InputFrames: 0
Max InputFrames: 0
Optimization: FF_CAP_PREFER_NONE
 
[ ExtendedInfoStruct ]
 
Plugin Major Version: 1
Plugin Minor Version: 4
 
[ Parameters ]
 
Num Parameters: 14
GetParameter Names
GetParameter Types
GetParameter Defaults
 
Parameter Details discovered before Instantiating
Shader Name  t(Text)  d(-1.06667321758613E37)
Update  t(Event)  d(0)
Select  t(Event)  d(0)
Edit  t(Event)  d(0)
Reload  t(Event)  d(0)
Speed  t(Stanard)  d(0.5)
X mouse  t(Stanard)  d(0.5)
Y mouse  t(Stanard)  d(0.5)
X mouse left  t(Stanard)  d(0.5)
Y mouse left  t(Stanard)  d(0.5)
Red  t(Stanard)  d(0.5)
Green  t(Stanard)  d(0.5)
Blue  t(Stanard)  d(0.5)
Alpha  t(Stanard)  d(1)
 
[ Instantiating a plugin instance ]
 
GetParameter Names
GetParameter Types
GetParameter Defaults
GetParameter Values
** Exception during GetParameter 0 **
** Exception during GetParameter 0 **
** Exception during GetParameter 0 **
** Exception during GetParameter 0 **
** Exception during GetParameter 0 **
** Exception during GetParameter 0 **
** Exception during GetParameter 0 **
** Exception during GetParameter 0 **
** Exception during GetParameter 0 **
** Exception during GetParameter 0 **
** Exception during GetParameter 0 **
** Exception during GetParameter 0 **
** Exception during GetParameter 0 **
** Exception during GetParameter 0 **
GetParameterDisplay Values
** Exception during GetParameterDisplay 0 **
** Exception during GetParameterDisplay 0 **
** Exception during GetParameterDisplay 0 **
** Exception during GetParameterDisplay 0 **
** Exception during GetParameterDisplay 0 **
** Exception during GetParameterDisplay 0 **
** Exception during GetParameterDisplay 0 **
** Exception during GetParameterDisplay 0 **
** Exception during GetParameterDisplay 0 **
** Exception during GetParameterDisplay 0 **
** Exception during GetParameterDisplay 0 **
** Exception during GetParameterDisplay 0 **
** Exception during GetParameterDisplay 0 **
** Exception during GetParameterDisplay 0 **
 
Parameter Details discovered after Instantiating
Shader Name  t(Text)  d(-1.06667321758613E37)
Update  t(Event)  d(0)
Select  t(Event)  d(0)
Edit  t(Event)  d(0)
Reload  t(Event)  d(0)
Speed  t(Stanard)  d(0.5)
X mouse  t(Stanard)  d(0.5)
Y mouse  t(Stanard)  d(0.5)
X mouse left  t(Stanard)  d(0.5)
Y mouse left  t(Stanard)  d(0.5)
Red  t(Stanard)  d(0.5)
Green  t(Stanard)  d(0.5)
Blue  t(Stanard)  d(0.5)
Alpha  t(Stanard)  d(1) 
```

Any ideas at all?
Much gratitude for any input you may have ...

**Comment by leadedge** [comment]
The exception is with GetParameter 0 which is a string. One possibility is a bug fix I have included in FFGL.cpp. See here ..

http://resolume.com/forum/viewtopic.php?f=14&t=10324

See if that fixes it.

**Comment by perrelet** [comment]
Thanks for the reply - very interesting to note that string bug there, will bare that in mind.

Good news - Just fixed my issue by compiling as release rather then debug in VS. 

All working sweet as pie now - so very grateful for your work - thankyou!

**Comment by trifox** [comment]
Dear unknown email user, i am horribly busy right now and i am most 
usually not be able to answer your questions,


you need to watch carefully for your parameter counting, they need to go 
consecutive from 0....any number with no holes in it
take the example files, and examine the parameters, you need to check 
the correct counting is valid and no whole in the sequence

but i assume you are just easily using the example shader? with the 
shaderloader ... hmm, this should be quite stable,  i assume you made 
some changes and this broke the code?
be sure to use a version control system like git for managing your code ....

all i can say is that since i am struggling heavily at my current job 
reading about various adminoistrative docker programming php stuff that 
needs my full attention in the next 3 monthes

did the examples i send to you work?

regards
ck

**Comment by perrelet** [comment]
Thanks for your reply - all has been working wonderfully since.

Re; Parameter counting, ive been using the preprocessor __COUNTER__ macro for those, which has been saving much trouble.

Thankyou
