### ISSUE TITLE
x64 version for Resolume 6?

### ISSUE THREAD

**Issue by luz-mala-zz** [leadedge/ShaderLoader#3]
Is there any posibilities of recompiling for working on latest resolume? (64bit)

**Comment by leadedge** [comment]
It would seem to be a straightforward task but there were many problems in doing so without re-writing the whole thing. I took a different approach entirely to generate plugins with the shader file and any images embedded in the plugin itself. (http://spout.zeal.co/forums/topic/shadertoysender-update/). There is a further update pending the result of testing. If you would like to help with that just email me using the address on the GitHub Overview page.

**Comment by luz-mala-zz** [comment]
Thank you very much for your reply.
I will look forward to work with shadertoysender.
